### ISSUE TITLE
DLL v3.1.11

### ISSUE THREAD

**Issue by revanmj** [beeradmoore/dlss-archive#2]
New [2.x DLL was released (v3.1.11)](https://github.com/NVIDIA/DLSS/blob/main/lib/Windows_x86_64/rel/nvngx_dlss.dll) with [new SDK version (v3.1.10)](https://github.com/NVIDIA/DLSS/releases/tag/v3.1.10)

**Comment by beeradmoore** [comment]
Thanks. Added!
