### ISSUE TITLE
DLSS v3.5

### ISSUE THREAD

**Issue by revanmj** [beeradmoore/dlss-archive#5]
NVIDIA submitted a commit do their repo with [nvngx_dlss.dll v3.5](https://github.com/NVIDIA/DLSS/raw/83e10e77c8ea0bd7ac8c4884c1aa4facad5910c2/lib/Windows_x86_64/rel/nvngx_dlss.dll) (in the comments they mention there is slightly newer 3.5 revision on [NVIDIAs dev site](https://developer.nvidia.com/rtx/dlss/get-started))

Source: https://www.reddit.com/r/nvidia/comments/16191av/dlss_super_sampling_sdk_350_released_nvngx/

**Comment by beeradmoore** [comment]
Thanks for letting me know. I'll push it through when I am home later.

**Comment by beeradmoore** [comment]
It's also interesting seeing there may be a seperate DLSSD just like there is a DLSSG

**Comment by revanmj** [comment]
> It's also interesting seeing there may be a seperate DLSSD just like there is a DLSSG

I kind of expected this when one more technical article mentioned Ray Reconstruction basically replaces denoisers. 

NVIDIA docs also mention it as a third module of DLSS (RR - Ray Reconstruction, SR - Super Resolution and FG - Frame Generation).

**Comment by beeradmoore** [comment]
I do worry that with the things streamline is doing that swapping DLLs may not work and we have to swap out the entire streamline system as well as one whole package.

But with the thoughts of also adding XESS and FSR into DLSS Swapper it also makes sense to have "Streamline" be something that is swappable as well.

**Comment by beeradmoore** [comment]
Closing, both of these have been added. Thanks again for the info.
